from turtle import Turtle, Screen

timmy = Turtle()
print(timmy)
my_screen = Screen()

timmy.shape("turtle")
timmy.speed(1)
timmy.pencolor("yellow")
timmy.forward(30)
timmy.pencolor("red")
timmy.left(50)
timmy.fd(30)
timmy.pencolor("blue")
timmy.left(50)
timmy.fd(30)
timmy.pencolor("orange")
timmy.left(50)
timmy.fd(30)
timmy.pencolor("green")
timmy.left(50)
timmy.fd(30)
timmy.pencolor("brown")
timmy.left(50)
timmy.fd(30)
timmy.pencolor("pink")
timmy.left(50)
timmy.fd(30)

my_screen.exitonclick()